config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :sql_templates
  mount Sidekiq::Web, at: '/sidekiq'

  resources :gadgets
  devise_for :users
  root to: 'pages#index'
  get "/live/gadgets", to: "gadgets#live_info"

end

app/models/sql_template.rb
require "singleton"
class SqlTemplate < ActiveRecord::Base
  validates :body, :path, presence: true
  validates :format, inclusion: Mime::SET.symbols.map(&:to_s)
  validates :locale, inclusion: I18n.available_locales.map(&:to_s)
  validates :handler, inclusion: ActionView::Template::Handlers.extensions.map(&:to_s)

  after_save do
    SqlTemplate::Resolver.instance.clear_cache
    Rails.cache.delete("view_cache:#{self.path}.#{self.locale}.#{self.format}.#{self.partial}")
  end

  class Resolver < ActionView::Resolver
    include Singleton

    protected

    def find_templates(name, prefix, partial, details)
      conditions = {
        path: normalize_path(name, prefix),
        locale: normalize_array(details[:locale]).first,
        format: normalize_array(details[:formats]).first,
        handler: normalize_array(details[:handlers]),
        partial: partial || false
      }
      maybe_fetch_from_catch(conditions).map do |record|
        initialize_template(record)
      end
    end

    def normalize_path(name, prefix)
      prefix.present? ? "#{prefix}/#{name}" : name
    end

    def normalize_array(array)
      array.map(&:to_s)
    end

    def initialize_template(record)
      source = record[:body]
      identifier = "SqlTemplate - #{record[:id]} - #{record[:path]}"
      handler = ActionView::Template::registered_template_handler(record[:handler])
      details = {
        format: Mime[record[:format]],
        updated_at: record[:updated_at],
        virtual_path: virtual_path(record[:path], record[:partial])
      }
      ActionView::Template.new(source, identifier, handler, details)
    end

    def virtual_path(path, partial)
      return path unless partial
      if index = path.rindex("/")
        path.insert(index + 1, "_")
      else
        "_#{path}"
      end
    end

    def maybe_fetch_from_catch(conditions)
      Rails.cache.fetch(keystring(conditions), :expires_in => 90.minutes) do
        to_hash ::SqlTemplate.where(conditions)
      end
    end

    def keystring(conditions)
      "view_cache:#{conditions[:path]}.#{conditions[:locale]}.#{conditions[:format]}.#{conditions[:partial]}"
    end

    def to_hash(records) 
      records.map do |record|
        {
          id: record.id,
          body: record.body,
          path: record.path,
          format: record.format,
          locale: record.locale,
          handler: record.handler,
          partial: record.partial
        }
      end
    end

  end
end

app/controllers/sql_templates_controller.rb
class SqlTemplatesController < ApplicationController
  before_action :set_sql_template, only: [:show, :edit, :update, :destroy]

  # GET /sql_templates
  # GET /sql_templates.json
  def index
    @sql_templates = SqlTemplate.all
  end

  # GET /sql_templates/1
  # GET /sql_templates/1.json
  def show
  end

  # GET /sql_templates/new
  def new
    @sql_template = SqlTemplate.new
  end

  # GET /sql_templates/1/edit
  def edit
  end

  # POST /sql_templates
  # POST /sql_templates.json
  def create
    @sql_template = SqlTemplate.new(sql_template_params)

    respond_to do |format|
      if @sql_template.save
        format.html { redirect_to @sql_template, notice: 'Sql template was successfully created.' }
        format.json { render :show, status: :created, location: @sql_template }
      else
        format.html { render :new }
        format.json { render json: @sql_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sql_templates/1
  # PATCH/PUT /sql_templates/1.json
  def update
    respond_to do |format|
      if @sql_template.update(sql_template_params)
        format.html { redirect_to @sql_template, notice: 'Sql template was successfully updated.' }
        format.json { render :show, status: :ok, location: @sql_template }
      else
        format.html { render :edit }
        format.json { render json: @sql_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sql_templates/1
  # DELETE /sql_templates/1.json
  def destroy
    @sql_template.destroy
    respond_to do |format|
      format.html { redirect_to sql_templates_url, notice: 'Sql template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sql_template
      @sql_template = SqlTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sql_template_params
      params.require(:sql_template).permit(:body, :path, :format, :locale, :handler, :partial)
    end
end

app/helpers/sql_templates_helper.rb
module SqlTemplatesHelper
end

app/views/sql_templates/_form.html.haml
= form_for(@sql_template) do |f| 
  - if @sql_template.errors.any? 
    #error_explanation
      %h2 #{pluralize(@sql_template.errors.count, "error")} prohibited this sql_template from being saved:
      %ul
        - @sql_template.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :body
    %br
    = f.text_area :body, class: "form-control"

  .form-group
    = f.label :path
    %br
    = f.text_field :path, class: "form-control"

  .form-group
    = f.label :format
    %br
    = f.text_field :format, class: "form-control"

  .form-group
    = f.label :locale
    %br
    = f.text_field :locale, class: "form-control"

  .form-group
    = f.label :handler
    %br
    = f.text_field :handler, class: "form-control"

  .form-group
    = f.label :partial
    %br
    = f.check_box :partial

  .actions
    = f.submit nil, class: 'btn btn-primary'

app/views/sql_templates/edit.html.haml
%h1 Editing Sql Template

= render :partial => "form"

= link_to 'Show', @sql_template  |
= link_to 'Back', sql_templates_path

app/views/sql_templates/index.html.haml
%p#notice= notice 

%h1 Listing Sql Templates

%table.table-striped.table
  %thead
    %tr
      %th Body
      %th Path
      %th Format
      %th Locale
      %th Handler
      %th Partial
      %th{:colspan => "3"}

  %tbody
    - @sql_templates.each do |sql_template| 
      %tr
        %td= sql_template.body 
        %td= sql_template.path 
        %td= sql_template.format 
        %td= sql_template.locale 
        %td= sql_template.handler 
        %td= sql_template.partial 
        %td= link_to 'Show', sql_template 
        %td= link_to 'Edit', edit_sql_template_path(sql_template) 
        %td= link_to 'Destroy', sql_template, method: :delete, data: { confirm: 'Are you sure?' } 

%br

= link_to 'New Sql template', new_sql_template_path

app/views/sql_templates/new.html.haml
%h1 New Sql Template

= render :partial => "form"

= link_to 'Back', sql_templates_path

app/views/sql_templates/show.html.haml
%p#notice= notice

%p
  %strong Body: #{@sql_template.body}

%p
  %strong Path: #{@sql_template.path}

%p
  %strong Format: #{@sql_template.format}

%p
  %strong Locale: #{@sql_template.locale}

%p
  %strong Handler: #{@sql_template.handler}

%p
  %strong Partial: #{@sql_template.partial}

= link_to 'Edit', edit_sql_template_path(@sql_template)
= link_to 'Back', sql_templates_path 